services:
  - type: web
    name: linux-server
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: "6969"
      - key: PLAYIT_SECRET
        value: "45c45b1a5c667718afca780abc8807ab8e31cdeb08cd972c205853f0293249ac"
